name: Events DeepDive Demo 1
on:
  pull_request:
#    types: [opened, edited]
     types:
       - opened
     # Any prs opened targeting these branches
     branches:
       - main
       - 'dev-*' # dev-new, dev-this-is-new
       - 'feat/**' # feat/new, feat/new/button
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*' # dev-new, dev-this-is-new
      - 'feat/**' # feat/new, feat/new/button
    paths-ignore:
    # This push event runs if any of the branches has a push and any workflow file is not changed
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm test
      - name: Build code
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."